### ISSUE TITLE
InstagramMedia entities aren't stored in database

### ISSUE THREAD

**Issue by nicohery** [andersbjorkland/instagram-display-extension#6]
The extension works fine but controller always re-download images in files/instagram with a new filename...
I tried to dump InstagramMedia entities and there are coherent datas. But nothing is saved in bolt_instagram_media mysql table.
I tried to manually add a mapping in services.yaml but instagram_media table is always empty.

**Comment by andersbjorkland** [comment]
Thanks for the heads up! I'll check up on this issue during the week. Mind sharing your setup, such as:
PHP- and Bolt-version. I understand you are running MySQL or MariaDB? The issue is probably the same regardless if it's the controller but it could be multiple issues as well.

**Comment by nicohery** [comment]
OK it was MySQL fields format issues.
I found the cause looking at the dev.log file (FYI there was no doctrine errors in profiler).
I saw ROLLBACK information so I tried to execute each query found in doctrine profiler.

I detect two different errors : 

1. Too long instagram url for varchar 255 field
`#1406 - Data too long for column 'instagram_url'`
I fixed it running `ALTER TABLE bolt_instagram_media CHANGE instagram_url instagram_url TEXT`

2. Emoji in caption
#1366 - Incorrect string value: '\xF0\x9F\x87\xA9\xF0\x9F...' for column 'caption'
I fixed it running `ALTER TABLE `bolt_instagram_media` CHANGE `caption` `caption` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`

**Comment by andersbjorkland** [comment]
Thanks a bunch for this info Nico! 👍
Does the issue with the re-download of images persist after you updated the table?

**Comment by nicohery** [comment]
No the issue with the re-download of images is also fixed !

**Comment by andersbjorkland** [comment]
Excellent. Then I'll be looking at fixing up the schema for bolt_instagram_media!
